version: '3.8'
services:
  prisma-migrate:
    container_name: prisma-migrate
    build:
      context: prisma
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: pgdata
